FROM tomcat:8.0

LABEL Owner="TOMCAT"

# Remove default Tomcat apps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy WAR generated by build.sh (repo root)
COPY ROOT.war /usr/local/tomcat/webapps/ROOT.war 

EXPOSE 8080

CMD ["catalina.sh", "run"]






